export const dummyProperties = [
	{
		id: 1,
		title: "Stone Manor Retreat",
		location: "Albuquerque, New Mexico",
		price: 895000,
		type: "Villa",
		status: "For Sale",
		bedrooms: 5,
		bathrooms: 3,
		area: 3240,
		featured: true,
		image: "/images/image1.jpg",
		description: "A character-filled stone residence with generous gardens, mature hedges, and a welcoming entrance courtyard."
	},
	{
		id: 2,
		title: "Cedar Grove Bungalow",
		location: "Toronto, Ontario",
		price: 1180000,
		type: "House",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 2,
		area: 1950,
		featured: false,
		image: "/images/image2.jpg",
		description: "A bright family bungalow with a landscaped front garden, private driveway, and a calm residential setting."
	},
	{
		id: 3,
		title: "Mountain View Residence",
		location: "Cape Town, South Africa",
		price: 2450000,
		type: "Villa",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 4,
		area: 4100,
		featured: true,
		image: "/images/image3.jpg",
		description: "A modern poolside home framed by dramatic mountain views, landscaped gardens, and expansive outdoor living areas."
	},
	{
		id: 4,
		title: "Coastal Terrace Home",
		location: "Cape Town, South Africa",
		price: 1760000,
		type: "House",
		status: "For Sale",
		bedrooms: 3,
		bathrooms: 3,
		area: 2680,
		featured: true,
		image: "/images/image4.jpg",
		description: "An airy coastal home with a sunlit terrace, swimming pool, and open views toward the beach."
	},
	{
		id: 5,
		title: "Palm Garden Estate",
		location: "Miami, Florida",
		price: 3200000,
		type: "Estate",
		status: "For Sale",
		bedrooms: 5,
		bathrooms: 5,
		area: 5250,
		featured: true,
		image: "/images/image5.jpg",
		description: "A refined contemporary estate with a resort-style pool, large lawn, and seamless indoor-outdoor entertaining."
	},
	{
		id: 6,
		title: "Hillside Modern Villa",
		location: "Los Angeles, California",
		price: 2890000,
		type: "Villa",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 4,
		area: 3760,
		featured: false,
		image: "/images/image6.jpg",
		description: "A crisp modern villa with multiple levels, private garages, and bright interiors designed for relaxed living."
	},
	{
		id: 7,
		title: "Sunlit Garden Cottage",
		location: "Austin, Texas",
		price: 745000,
		type: "House",
		status: "For Sale",
		bedrooms: 3,
		bathrooms: 2,
		area: 1820,
		featured: false,
		image: "/images/image7.jpg",
		description: "A welcoming white cottage with generous paved grounds, bright rooms, and a peaceful garden setting."
	},
	{
		id: 8,
		title: "Clifftop Pool House",
		location: "Cape Town, South Africa",
		price: 2150000,
		type: "Villa",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 3,
		area: 3480,
		featured: true,
		image: "/images/image8.jpg",
		description: "A striking pool house with wide glass openings, mountain scenery, and an effortless indoor-outdoor layout."
	},
	{
		id: 9,
		title: "Oceanfront Courtyard Villa",
		location: "Cape Town, South Africa",
		price: 2680000,
		type: "Villa",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 4,
		area: 3920,
		featured: false,
		image: "/images/image9.jpg",
		description: "A private ocean-facing villa with a generous pool deck, mountain backdrop, and elegant entertaining spaces."
	},
	{
		id: 10,
		title: "Contemporary Pool Residence",
		location: "Cape Town, South Africa",
		price: 2350000,
		type: "House",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 3,
		area: 3300,
		featured: false,
		image: "/images/image10.jpg",
		description: "A private contemporary residence with a sparkling pool, timber deck, and lush lawn for outdoor gatherings."
	},
	{
		id: 11,
		title: "Seaside Shingle Home",
		location: "Nantucket, Massachusetts",
		price: 1995000,
		type: "House",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 3,
		area: 2740,
		featured: true,
		image: "/images/image11.jpg",
		description: "A classic shingle-style home with a wide covered porch, mature landscaping, and an inviting family layout."
	},
	{
		id: 12,
		title: "Bright Coastal Entertainer",
		location: "Cape Town, South Africa",
		price: 1890000,
		type: "Villa",
		status: "For Sale",
		bedrooms: 4,
		bathrooms: 3,
		area: 3060,
		featured: false,
		image: "/images/image12.jpg",
		description: "A light-filled coastal villa with an inviting pool, open-plan living, and sweeping views from the upper terrace."
	}
];